name = "worker-a"
main = "./index.ts"
compatibility_date = "2024-12-30"

services = [{ binding = "WORKER_B", service = "worker-b" }]
routes = [{ pattern = "dev.promptify.ai/*", zone_name = "promptify.ai" }]
